all:
  vars:
    ansible_user: root
  children:
    releasy_app:
      hosts:
        releasy:
          ansible_host: 10.0.1.10
    releasy_db:
      hosts:
        releasy:
          ansible_host: 10.0.1.10
    traefik:
      hosts:
        releasy:
          ansible_host: 10.0.1.10
